#!/usr/bin/env bash
# dotfiles requires git and pip
if [ `uname` == "Darwin" ]; then
  brew install git python
else
  sudo apt-get -y --force yes install git\
                python-pip\
                python-dev\
                build-essential
fi


git clone git@github.com:joshblum/dotfiles.git ~/.dotfiles || git clone https://github.com/joshblum/dotfiles.git ~/.dotfiles
cd ~/.dotfiles && make
cd - && rm -- "$0"
