"--------------
" Load pathogen
"--------------
execute pathogen#infect()
call pathogen#helptags()

source $HOME/.vim/custom/settings.vim
source $HOME/.vim/custom/mappings.vim
source $HOME/.vim/custom/plugins.vim
